- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.2
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
      language_version: python3
    - id: detect-private-key


- repo: https://github.com/psf/black
  sha: 19.3b0
  hooks:
    - id: black
      language_version: python3
      exclude: migrations


- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      language_version: python3
      exclude: migrations


      # - repo: https://github.com/timothycrosley/isort
      #   rev: 4.3.21
      #   hooks:
      #     - id: isort
      #       entry: isort -c --check-only -sp ./.isort.cfg
      #       language_version: python3
