version: "3"

services:
  udp-server:
    environment:
      - UDPSERVER_HOST
      - UDPSERVER_PORT
      - UDPSERVER_PROTOCOL
      - DJANGO_API_TOKEN
      - DJANGO_API_LOGS_SERVICE
    build:
      context: .
      dockerfile: ./compose/local/udp-server/Dockerfile
    command: /start
    ports:
      - "5555:5555/udp"
